# Generated by Django 4.1.3 on 2024-06-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='audio_permissions',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group_permissions',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='role',
            field=models.CharField(default='member', max_length=255),
            preserve_default=False,
        ),
    ]
