# Generated by Django 4.1.3 on 2024-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_sound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='name',
            field=models.CharField(default='no name', max_length=255),
            preserve_default=False,
        ),
    ]
