# Generated by Django 4.1 on 2024-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score_sound", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audioscore",
            old_name="audio",
            new_name="audio_url",
        ),
        migrations.RemoveField(
            model_name="audioscore",
            name="details",
        ),
        migrations.AddField(
            model_name="audioscore",
            name="rhythm",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="audioscore",
            name="scale",
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="audioscore",
            name="tempo",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
