# Generated by Django 4.1 on 2024-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score_sound", "0002_rename_audio_audioscore_audio_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("beats", models.JSONField()),
            ],
        ),
    ]
