# Generated by Django 4.1 on 2024-03-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=10, null=True)),
                ("email", models.EmailField(max_length=255, null=True)),
            ],
        ),
    ]
